services:
  - type: web
    name: news-capsule
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm run render:build
    startCommand: npm run render:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: false
        value: "10000"
      - key: BASE_PATH
        value: "/"
      - key: NEWSAPI_KEY
        sync: false
